- name: Infrastructure Play
  hosts: infrastructure
  become: true
  roles:
    - initial_setup
    - dns
    - resolv
    - dhcp
    - ntp
    - virtualization
    - network_config
    - hosts_updater
