---
- name: Install ISC DHCP Server
  ansible.builtin.yum:
    name: dhcp-server
    state: present
  tags:
    - dhcp_config

- name: Configure ISC DHCP Server
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - dhcp_config

- name: Enable and start ISC DHCP service
  ansible.builtin.service:
    name: dhcpd
    state: started
    enabled: true
  tags:
    - dhcp_config
