- name: Install ISC DHCP Server
  ansible.builtin.yum:
    name: dhcp-server
    state: present

- name: Configure ISC DHCP Server
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf

- name: Enable and start ISC DHCP service
  ansible.builtin.service:
    name: dhcpd
    state: started
    enabled: yes

