---
- name: Install BIND DNS Server
  ansible.builtin.yum:
    name: bind
    state: present

- name: Start and Enable Named Service
  service:
    name: named
    state: started
    enabled: true

- name: Configure BIND DNS Server
  ansible.builtin.copy:
    src: "/home/devcloud/intel-user-lab-ansible/roles/dns/templates/named.conf.j2"
    dest: "/etc/named/named.conf"
    owner: root
    group: named
    mode: '0644'

- name: Configure Reverse DNS Zone
  ansible.builtin.copy:
    src: "/home/devcloud/intel-user-lab-ansible/roles/dns/templates/db.10.10.10.j2"
    dest: "/var/named/db.10.10.10"
    owner: root
    group: named
    mode: '0644'

- name: Configure Forward DNS Zone
  ansible.builtin.copy:
    src: "/home/devcloud/intel-user-lab-ansible/roles/dns/templates/db.lab.com.j2"
    dest: "/var/named/db.lab.com"
    owner: root
    group: named
    mode: '0644'
