dns_forward_zone: "lab.com"
dns_reverse_zone: "10.10.10.in-addr.arpa"
dns_records:
  - { name: 'primary', ip: '10.10.10.14' }
  - { name: 'server1', ip: '10.10.10.12' }
  - { name: 'server2', ip: '10.10.10.11' }
  - { name: 'server3', ip: '10.10.10.13' }

