- name: Install Virtualization Packages
  ansible.builtin.yum:
    name:
      - libvirt
      - virt-manager
      - qemu-kvm
      - libvirt-client
    state: present

- name: Enable and start libvirtd service
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: yes

- name: Add current user to libvirt group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: libvirt
    append: yes

